# Generated by Django 4.2 on 2023-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0006_product_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="Product_details",
        ),
    ]
