# Generated by Django 4.2 on 2023-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0008_product_availability_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
