# Generated by Django 4.2 on 2023-05-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0011_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="total",
        ),
    ]
