# Generated by Django 4.2 on 2023-05-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0012_remove_cart_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="grand_total",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.IntegerField(null=True),
        ),
    ]
