# Generated by Django 4.2 on 2023-05-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0014_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="grand_total",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total",
        ),
    ]
