# Generated by Django 4.2 on 2023-05-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0019_alter_checkout_pincode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="cart",
        ),
    ]
