# Generated by Django 4.2 on 2023-05-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0022_checkout_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="user",
        ),
    ]
