# Generated by Django 4.2 on 2023-05-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0023_remove_checkout_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Saleoff",
        ),
    ]
