# Generated by Django 4.2 on 2023-05-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0024_delete_saleoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
