# Generated by Django 4.2 on 2023-05-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0025_product_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Featured",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_image", models.ImageField(upload_to="media/")),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
