# Generated by Django 4.2 on 2023-05-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0026_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="featured",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fresh.category",
            ),
        ),
    ]
