# Generated by Django 4.2 on 2023-05-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0027_featured_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="featured",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
