# Generated by Django 4.2 on 2023-05-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fresh", "0029_remove_featured_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
    ]
